theme: jekyll-theme-cayman

# Site settings
title: KXC Blog
SEOTitle: 空心菜的博客 | KXC Blog
header-img: img/home-bg.jpg
email: lzhujian@gmail.com
description: "关于程序与设计、黑客与画家 | Software Engineer，UX Designer | 这里是 @kxc空心菜 的个人博客，与你一起发现更大的世界。"
keyword: "博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://lzhujian.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    lzhujian
